/* jQuery tubular plugin
|* by Sean McCambridge
|* http://www.seanmccambridge.com/tubular
|* version: 1.0
|* updated: October 1, 2012
|* since 2010
|* licensed under the MIT License
|* Enjoy.
|*
|* Thanks,
|* Sean */

(function(e,t){var n={ratio:16/9,videoId:"ZCAnLxRvNNc",mute:true,repeat:true,width:e(t).width(),wrapperZIndex:99,playButtonClass:"tubular-play",pauseButtonClass:"tubular-pause",muteButtonClass:"tubular-mute",volumeUpClass:"tubular-volume-up",volumeDownClass:"tubular-volume-down",increaseVolumeBy:10,start:0};var r=function(r,i){var i=e.extend({},n,i),s=e("body");$node=e(r);var o='<div id="tubular-container" style="overflow: hidden; position: fixed; z-index: 1; width: 100%; height: 100%"><div id="tubular-player" style="position: absolute"></div></div><div id="tubular-shield" style="width: 100%; height: 100%; z-index: 2; position: absolute; left: 0; top: 0;"></div>';e("html,body").css({width:"100%",height:"100%"});s.prepend(o);$node.css({position:"relative","z-index":i.wrapperZIndex});t.player;t.onYouTubeIframeAPIReady=function(){player=new YT.Player("tubular-player",{width:i.width,height:Math.ceil(i.width/i.ratio),videoId:i.videoId,playerVars:{controls:0,showinfo:0,modestbranding:1,wmode:"transparent"},events:{onReady:onPlayerReady,onStateChange:onPlayerStateChange}})};t.onPlayerReady=function(e){u();if(i.mute)e.target.mute();e.target.seekTo(i.start);e.target.playVideo()};t.onPlayerStateChange=function(e){if(e.data===0&&i.repeat){player.seekTo(i.start)}};var u=function(){var n=e(t).width(),r,s=e(t).height(),o,u=e("#tubular-player");if(n/i.ratio<s){r=Math.ceil(s*i.ratio);u.width(r).height(s).css({left:(n-r)/2,top:0})}else{o=Math.ceil(n/i.ratio);u.width(n).height(o).css({left:0,top:(s-o)/2})}};e(t).on("resize.tubular",function(){u()});e("body").on("click","."+i.playButtonClass,function(e){e.preventDefault();player.playVideo()}).on("click","."+i.pauseButtonClass,function(e){e.preventDefault();player.pauseVideo()}).on("click","."+i.muteButtonClass,function(e){e.preventDefault();player.isMuted()?player.unMute():player.mute()}).on("click","."+i.volumeDownClass,function(e){e.preventDefault();var t=player.getVolume();if(t<i.increaseVolumeBy)t=i.increaseVolumeBy;player.setVolume(t-i.increaseVolumeBy)}).on("click","."+i.volumeUpClass,function(e){e.preventDefault();if(player.isMuted())player.unMute();var t=player.getVolume();if(t>100-i.increaseVolumeBy)t=100-i.increaseVolumeBy;player.setVolume(t+i.increaseVolumeBy)})};var i=document.createElement("script");i.src="//www.youtube.com/iframe_api";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(i,s);e.fn.tubular=function(t){return this.each(function(){if(!e.data(this,"tubular_instantiated")){e.data(this,"tubular_instantiated",r(this,t))}})}})(jQuery,window)